apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: production
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.16-192.168.1.24
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: wordpress
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.15/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advert
  namespace: metallb-system

